### PR TITLE
Fix all syntax errors and translate on russian language.

### PR DESCRIPTION
**Pull request by themestl**
For translate key you can use:
```php
$implade->getLang('some-key', array('search' => 'replace'));
```

### CODE REVIEW

**Comment by Zadezter** [comment]
Thank you so much, @themestl.. :D

**Comment by xXNiceYT** [comment]
@Zadezter I said I wanna to fix it but u said wait -_-

**Comment by Zadezter** [comment]
I set my AFK message about to fix syntax error and sent screenshot on #media channel yesterday, but you just go offline.

**Comment by Wolfkid200444** [comment]
...

**Pull request merged**
