### PR TITLE
Added new Gamemodes and Legendary Trident features + Made some changes at codes!

### PR DESCRIPTION
**Pull request by Zadezter**

### CODE REVIEW

**Comment by Zadezter** [comment]
I should change a few codes before I merge this. :3

**Comment by Wolfkid200444** [comment]
You Should Add More in the CAPSLimmit and SWEARFile

**Comment by Zadezter** [comment]
@Wolfkid200444 AntiCaps and AntiSwearing were moved to **listeners** folder.

**Comment by Zadezter** [comment]
Last commits I can do. So it's time to merge.

**Pull request merged**
