### PR TITLE
Changed every codes.

### PR DESCRIPTION
**Pull request by Leomord**
If you see any invalid changed codes, please change it idk. It will make errors if I always did.

### CODE REVIEW

**Comment by Wolfkid200444** [comment]
wdym?

**Comment by Leomord** [comment]
@Wolfkid200444 i always make it error heheh

**Comment by Leomord** [comment]
@xXNiceYT @FreeGamingHere @Wolfkid200444 @Zadezter idk what am I have done.

**Comment by Leomord** [comment]
Well uh, death human(corpse) has a problem to spawn after death. Will you help me? Sorry for bothering. @xXNiceYT @FreeGamingHere @Zadezter @Wolfkid200444?

**Comment by Zadezter** [comment]
And third, **I figuring out how to fix foreach() error** for ```[]```

**Comment by xXNiceYT** [comment]
Hey kids

**Comment by Wolfkid200444** [comment]
Hi

**Comment by Leomord** [comment]
Hey you, non-funny guy, @xXNiceYT

**Comment by Zadezter** [comment]
U not helpful freak collaborators

**Pull request merged**
